### ISSUE TITLE
How to get the `serialbox2/examples/fortran/perturbation` compiled?

### ISSUE THREAD

**Issue by adamryczkowski** [eth-cscs/serialbox2#10]
I think it is disabled in CMake (AFAIK Cmake doesn't even mention this directory), and when I tried to fix it, I spend 2 hours and gave up.

But this example is exactly the thing we would like to have working to use the serialbox2 as a drop-in replacement for SB1.

**Comment by thfabian** [comment]
Hey Adam,

The example is intentionally disabled from the main CMake project as it is a **stand-alone** example. This means you have to use Serialbox as an external library and this example demonstrates how this is being done i.e guides you through the process of setting up CMake to link against Serialbox.

To get it working, proceed the following:

 - First you need to compile and *install* Serialbox **with** Fortran enabled (see https://eth-cscs.github.io/serialbox2/Building.html). By default, Serialbox is installed in `serialbox2/install`. Something like:
    ```bash
    git clone https://github.com/eth-cscs/serialbox2.git
    cd serialbox2
    mkdir build
    cd build
    cmake -DSERIALBOX_ENABLE_FORTRAN=ON ../
    make
   make install
    ```
    should do the trick.

- Now we can compile the example (or any other project which uses Serialbox for that matter). Note that this is completely decoupled from the build we did before (it only *uses* the installed headers and binaries!).
  1. Change to the directory `serialbox2/examples/fortran/perturbation`
    ```bash
    cd  serialbox2/examples/fortran/perturbation
    ```
  2. Create a build directory
    ```bash
    mkdir build
    cd build
    ```
  3. Now we are ready to run CMake for this example. Take a look at `examples/fortran/perturbation/CMakeLists.txt` which has a very detailed explanation on what exactly is going on and how to use CMake with Serialbox. Further, the documentation on how to use Serialbox as an external project (https://eth-cscs.github.io/serialbox2/Usage.html) may be of use. Basically the only thing you need to provide is the install location of Serialbox. For this example however, the location of Serialbox (`SERIALBOX_ROOT`) is hard-coded i.e it assumes the installation of Serialbox is in `../../../install` (but you can also remove this line and pass `SERIALBOX_ROOT` via command-line to have a more realistic environment). Now, this simply means we can run CMake in the build directory:
  ```bash
  cmake ../
  ```
  which will create all the build files directly in  `serialbox2/examples/fortran/perturbation/build` and a follow up `make` will build the example. Note that for this example you *need* to compile Serialbox with Fortran enabled (https://eth-cscs.github.io/serialbox2/Building.html#building-the-fortran-interface) otherwise the CMake module will complain.

Let me know if there are any further issues.

**Comment by adamryczkowski** [comment]
No, the cmake in the `serialbox2/examples/fortran/perturbation/build` doesn't run properly. I get 

```
CMake Error at cmake/FindSerialbox.cmake:109 (file):
  file failed to open for reading (No such file or directory):

    /home/adam/tmp/serialbox2/examples/fortran/perturbation/../../../install/include/serialbox/core/Config.h
Call Stack (most recent call first):
  CMakeLists.txt:40 (find_package)


CMake Error at cmake/FindSerialbox.cmake:130 (math):
  math cannot parse the expression: " / 100000": syntax error, unexpected
  exp_DIVIDE, expecting exp_OPENPARENT or exp_NUMBER (2)
Call Stack (most recent call first):
  CMakeLists.txt:40 (find_package)


CMake Error at cmake/FindSerialbox.cmake:131 (math):
  math cannot parse the expression: " / 100 % 1000": syntax error, unexpected
  exp_DIVIDE, expecting exp_OPENPARENT or exp_NUMBER (2)
Call Stack (most recent call first):
  CMakeLists.txt:40 (find_package)


CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:829 (message):
  When requesting a specific version of Boost, you must provide at least the
  major and minor version numbers, e.g., 1.34
Call Stack (most recent call first):
  cmake/FindSerialbox.cmake:235 (find_package)
  CMakeLists.txt:40 (find_package)


-- Could NOT find Boost
CMake Warning at cmake/FindSerialbox.cmake:256 (message):
  Serialbox: Boost (.) NOT found! (Found Boost 1.58)

  Required components:

   - filesystem
   - system

Call Stack (most recent call first):
  CMakeLists.txt:40 (find_package)


CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find Serialbox.  (Try setting SERIALBOX_ROOT in the env): Found
  unsuitable version "..", but required is at least "2.0.0" (found
  /home/adam/tmp/serialbox2/examples/fortran/perturbation/../../../install)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindSerialbox.cmake:324 (find_package_handle_standard_args)
  CMakeLists.txt:40 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/adam/tmp/serialbox2/examples/fortran/perturbation/build/CMakeFiles/CMakeOutput.log".
See also "/home/adam/tmp/serialbox2/examples/fortran/perturbation/build/CMakeFiles/CMakeError.log".
```

I stumbled the very same error yesterday. It seems that the CMake script is unable to read the installed Serialbox version properly, one of the reason is due to bad paths. Providing the proper installation path manually in the CMake code didn't fix it to me, so I gave up. I'll reinstall Ubuntu and file another issue shortly, so there will be no interferences from the rest of the system.

**Comment by adamryczkowski** [comment]
...and by the way, I have both filesystem and system components of the Boost library installed (otherwise I wouldn't be able to compile the serialbox2 itself)

**Comment by adamryczkowski** [comment]
OK. Everything works. Thanks!
