### ISSUE TITLE
Is there support for Netcdf from within the Fortran code?

### ISSUE THREAD

**Issue by adamryczkowski** [eth-cscs/serialbox2#12]
I want the Fortran code to serialize a field directly into netcdf format. Is that supported/possible?

**Comment by thfabian** [comment]
Hey Adam,

This is certainly possible as the Fortran code is a simple warpper around the C code. This being said, you would need to modify one line in `fs_create_serializer` in `m_serialize.f90`. The current archive is hard-coded to `"Binary"` (https://github.com/eth-cscs/serialbox2/blob/master/src/serialbox-fortran/m_serialize.f90#L317) and this should be `"NetCDF"` to use NetCDF archives.

The cleanest way is to add a new parameter for the archive to `fs_create_serializer`. I didn't to this because this probably breaks backwards compatibility, not sure if you can set default values for parameters in Fortran.

**Comment by adamryczkowski** [comment]
Thank you! 
I will try to test this today. 

Your solution requires us to modify the code. No problem except that it will put us badly off-stream, and force us to maintain our fork of the serialbox2. 
Is there any place in your roadmap for the serialbox2 for supporting the NetCDF serializer *without requireing users to modify upstream repository*? 

If yes, I may improvise a pull request that adds a function or two for the purpose. I am not a Fortran programmer myself, but maybe I can enlist my colleagues who are. Do you have any pointers for us on how to implement the support for NetCDF, so it agrees with your vision and project structure (which we don't know at this point)?

**Comment by adamryczkowski** [comment]
I suppose there are optional arguments in Fortran 90: http://stackoverflow.com/a/3122736/1261153 

As I wrote, I am not a Fortran programmer myself, so I can't tell you more.

**Comment by chovyy** [comment]
I have created a solution. Check out my pull request #13.

**Comment by pspoerri** [comment]
very nice

**Comment by thfabian** [comment]
Merged #13
