### ISSUE TITLE
Review linking of libs shared/static

### ISSUE THREAD

**Issue by havogt** [eth-cscs/serialbox2#72]

**Comment by havogt** [comment]
link all boost libs staticaly?

```-lboost_chrono -lboost_date_time -lboost_atomic -lboost_regex -lboost_thread```

**Comment by havogt** [comment]
We discussed that we dynamically link boost. The only library should be `program_options` and `filesystem` after #83.
This requires:
- to propagate library flags from Serialbox2 installation to the cosmo makefile.
- put boost (and Serialbox) into `LD_LIBRARY_PATH` at runtime

**Comment by havogt** [comment]
I discussed again with @pspoerri and came to the conclusion that it is very inconvenient if the user has to deal with the dynamic library for running `cosmo_serialize`.

Let's try to solve our concerns from yesterday against static linking. If I remember correctly the concern was compiling Serialbox and STELLA with different boost versions?
Can someone find a case where this is a problem?

The following cases should be fine:
- cosmo is compiled for serialization: the dycore is not used -> no problem.
- the dycore (i.e. STELLA) is compiled with verification: serialbox is used -> we can import the boost dependency from serialbox. There is no real need to use a different boost version?
- the dycore (STELLA) is compiled without serialbox -> no problem

**Comment by thfabian** [comment]
Well statically linking boost of course works as long as you make sure to always link against the same boost version serialbox was compiled with. For example, if serialbox was compiled with boost 1.58, you *have* to use boost 1.58 in all upstream dependencies which use serialbox. The problem you may run in to is that there is usually no linker error if you link against a newer version of boost (for example 1.60) -- it's extremely hard to debug these kind of errors.

This is I think the reason libraries at very bottom of the software stack are linked dynamically (same applies to zlib).

**Comment by pspoerri** [comment]
> Well statically linking boost of course works as long as you make sure to always link against the same boost version serialbox was compiled with. For example, if serialbox was compiled with boost 1.58, you have to use boost 1.58 in all upstream dependencies which use serialbox. The problem you may run in to is that there is usually no linker error if you link against a newer version of boost (for example 1.60) -- it's extremely hard to debug these kind of errors.

This is a problem we typically solve with build scripts. Moving this to the runtime will make the problems worse. E.g. /project is not mounted on daint.

**Comment by andyspiros** [comment]
> Well statically linking boost of course works as long as you make sure to always link against the same boost version serialbox was compiled with.

I don't fully understand this. If Serialbox creates a static library, there is no linking involved yet, right? The linking is done at the end and there won't be "competing" boost version, since a single boost library will be linked in (you just need to make sure to put `-lboost_filesystem` after `-lSerialbox`.

At linking time, there could be a problem if the version of boost linked in does no export the same ABI as the headers used in the compilation of Serailbox. That will result in linking errors.

Another problem could be if the boost linked in uses the same ABI of the headers used in Serialbox for a different behavior. Say that boost-1.58 uses `char boost::myfunction (int)` to convert an `int` to a `char` the same way a `static_cast` does it (or Pyhton [`ord`](https://docs.python.org/3/library/functions.html#chr)), while version 1.63 changes this to a conversion equivalent to `to_string`, where only the leading character is returned. If Serialbox compiles with version 1.63 but cosmo is then linked with 1.58 the linking would succeed, but the runtime behavior will be wrong, which is the worst possible case. But I'm pretty sure this is impossible because boost has a policy of not changing the ABI across minor versions. And anyway this problem would still appear in the dynamic linking case.

If you compile Serialbox as a shared library and link boost statically, I think all problems are solved. The boost library will be part of `libSerialbox.so`, used there internally and not exported by the ABI of the dynamic library (not 100% about the last point). Then cosmo can link statically against a potentially different version of boost for the usage of boost in STELLA and the dycore, but this version will not interfere with Serialbox, because it has its own version of boost included in it. Can this be a solution.

Note that my personal preference still goes to have everything linked dynamically because this is the clean general solution for more than one reason. But I'm trying to play the devil's advocate and see if static linking or a mixed approach can be better, and to me it looks like the answer is yes...

**Comment by havogt** [comment]
The main point against dynamic linking is how to expose the library path to the user (and the lib might not be available at runtime if located in /project on daint). Any solutions to that?

**Comment by thfabian** [comment]
I agree with you on everything but

> But I'm pretty sure this is impossible because boost has a policy of not changing the ABI across minor versions. And anyway this problem would still appear in the dynamic linking case.

Keeping ABI compatible accross versions is an insane task (see this talk https://www.youtube.com/watch?v=Ia3IDPjA-d0) -- Are you sure this is there policy, this would basically stall development. For dynamic linking this problem can be partially solved using CMakes interface link libraries which encode the exact path to the boost libraries which were used for compilation (an application can load different boost libraries at runtime from different paths I think) see https://cmake.org/Wiki/CMake_RPATH_handling

I don't know how to do it on Daint. If you don't want to load modules than you have to go with static linking and hope you never link with different boost versions I think.

**Comment by havogt** [comment]
I tried to mix boost versions and I get:
>warning: #warning "Boost version used for compilation does not match current Boost version!" [-Wcpp]

I guess we are fine with static linking?

**Comment by thfabian** [comment]
Ahh, I forgot about that ;) I think I added this warning after I debugged such an issue for hours!

**Comment by havogt** [comment]
Solved by using std::experimental::filesystem.
